development:
  adapter: postgresql
  encoding: utf8
  database: student_sat_portal_final_dev
  host: localhost
  pool: 5
  username: postgres
  password: prashanth320

test:
  adapter: postgresql
  encoding: utf8
  database: student_sat_portal_test
  host: localhost
  pool: 5
  username: postgres
  password: prashanth320

production:
  adapter: postgresql
  encoding: utf8
  database: 
  pool: 5
  username: 
  password: 